api_platform:
    title: 'TuOferta'
    description: 'Api for TuOferta'
    version: '0.1.0'
    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    enable_fos_user: true
    allow_plain_identifiers: true
    collection:
        pagination:
            maximum_items_per_page: 50
            items_per_page: 10
            enabled: false
            items_per_page_parameter_name: itemsPerPage
            client_items_per_page: true
            enabled_parameter_name: pagination
    oauth:
        enabled: true
        flow: password
        tokenUrl: '/api/login'
        clientId: '%env(CLIENT_ID)%'
        clientSecret: '%env(CLIENT_SECRET)%'

    mapping:
          paths:
            - '%kernel.project_dir%/config/packages/apiplatform'
