resources:
    App\Entity\Rate:
        attributes:
            pagination_enabled: false
            normalization_context:
                groups: ['rate-read']
            denormalization_context:
                groups: ['rate-write']
            enable_max_depth: true
        collectionOperations:
            get:
                method: 'GET'

            post:
                method: 'POST'

        itemOperations:

            get:
                method: 'GET'
                access_control: is_granted('ROLE_USER')
                swagger_context:
                    summary: 'Devuelve una tarifa'

#            filter:
#                method: 'GET'
#                route_name: 'api_user_filter'
#                access_control: is_granted('ROLE_USER')
#                swagger_context:
#                    summary: 'Filtra usuarios por nombre dni o cif'

            put:
                method: 'PUT'
                access_control: is_granted('ROLE_USER')
                swagger_context:
                  summary: 'Actualiza una tarifa'

            delete:
                            method: 'DELETE'
                            path: '/rate/{id}'
                            swagger_context:
                                summary: 'Borra  una tarifa'
                            requirements:
                                id: '\d+'
                            access_control: is_granted('ROLE_USER')

