easy_admin:
    entities:    
        Subcategory:
            class: App\Entity\Subcategory
            label: menu.subcategory
            controller: App\Controller\Admin\Model\CategoryController
            show:
                title: menu.subcategory
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'name', label: 'name' }
                    - { property: 'category', label: 'category'}


            edit:
                title: menu.subcategory
                fields:
                    - { property: 'name', label: 'name'}
                    - { property: 'category', label: 'category'}

            form:
               title: menu.subcategory
               fields:
                   - { property: 'name', label: 'name' }

