easy_admin:
    entities:    
        Subcategory:
            class: App\Entity\Subcategory
            label: menu.subcategory
            show:
                title: menu.subcategory
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'name', label: 'name' }
                    - { property: 'category.name', label: 'category'}


            edit:
                title: menu.subcategory
                fields:
                    - { property: 'name', label: 'name'}
                    - { property: 'category.name', label: 'category'}

            form:
               title: menu.subcategory
               fields:
                   - { property: 'name', label: 'name' }
                   - { property: 'category.name', label: 'category',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }