imports:
    - { resource: security.yml }
    - { resource: services.yml }
    
parameters:
    locale: es

framework:
    esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    serializer:
        enable_annotations: true
        cache: serializer.mapping.cache.apcu
    templating:
        engines: ['twig', 'php']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
        
        
        # Twig Configuration
twig:
    globals:
        client_id: "%client_id_stripe%"
        base_url: "%api_url%"
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        metadata_cache_driver: apcu
        query_cache_driver: apcu
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            VouzzerBundle:
                mapping: true
                type: yml
                dir: Resources/config/doctrine
                prefix: 'Zinkers'
                alias: 'Vouzzer'
            FOSUserBundle: ~
            FOSOAuthServerBundle: ~
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
                
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    service:
         mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%env(resolve:MAILER_USER)%"
        sender_name: "%env(resolve:MAILER_NAME)%"
        
        
fos_oauth_server:
    db_driver: orm
    client_class: App\Entity\Client
    access_token_class: App\Entity\AccessToken
    refresh_token_class: App\Entity\RefreshToken
    auth_code_class: App\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username
        options:
            supported_scopes: read
        
moskalyovd_fcm:
    server_key:  "%env(resolve:API_KEY)%"